### ISSUE TITLE
Responsive Website is not rendering very well ın mobile

### ISSUE THREAD

**Issue by berke-volkan** [hackclub/browserbuddy#41]
Long questions in the "FAQ" section are overflowing from the box and also when you click on one of the questions, the other questions are not visible

**Comment by JosiasAurel** [comment]
@berke-volkan thanks for reporting. please could you share a screenshot?

**Comment by berke-volkan** [comment]
![Image](https://github.com/user-attachments/assets/05095c41-a87f-4b75-bd84-e3e426ed49f3)
